language: java
before_install:
  - 'mkdir -p ${HOME}/.m2'
  - 'cp .travis/maven-settings.xml ${HOME}/.m2/settings.xml'
  - 'bash .travis/setup-secrets.sh'
  - . .travis/install-openjdk.sh
install: './mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V'
script:
  - 'bash .travis/deploy.sh'

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.cache"

env:
  global:
  - secure: "skyslMaJ8N9VY0FQ60bXMulFo1RH3xuqWQDm29DFp146qnLFysdQRTUaTPOZWsS/vKPA9unUWMEA7HVR2HKv7MxmR4t+om5Kzo0jrWDH2Xx6jTec/LXq7BT8VJzPf7ikmWXjuMN3y1FoAzcSP1kyGQRo07WTkjsICA3wbchNo+8NqmXk5nq2rpx3AOkMBkwiI25ldqidVCzshULEQvMiy2KI/XiI4yLIaiQNE7eN14hbpY8wmHl8GO05MfonfjPPm9qhpDjaamckL37ce1ByB7fb53qTT9VR0vaHJslW2Jci1t/ClQv6EKsmWckH0EZ23/Z0KA/PdNrvhmUHbH8zvAFd3KviTtmSrm+P06Ep1JBTwqxkHZuogyKQT9h5UqH6ioGMXvZqcH8ioLQan5j+uxy6dTx0OFROrIM3n6q0rd/1MWGi0rHNuCLtD/9CatXaox4Aoxf3zuBMcJDNkP4sOuHTi9ib+lYV3r/Jte1TL4o2yStYQ4J4hoqiLYZzTcMp1+q4AOflmA0WlGJHWtvvV/T+kKSkMRE1Z7Qyv8RhnVc5kEk1yvLCpp0lrpvdC0OKxPgWiqyrjPPTJtAmAB2Xqv+P66fDp8CvjaLuqCir+0kESV5J6pXC8Iwz0Ee9hsmU+uokHj3Egm5cjqyF5xBfjN5aWWASSq9oGezdXioLObw="
  - secure: "MxmtUcFgN1Iy2yq0QmR23PPEymNkXkn1nRZLaHy9UxHYC9hgloZi7n4k7Y4DAJbM42i6+twT1WVUhmV33Uzi/b1t1gpyVJGKGIg71Lf/B4FfEEY7/xvVNzSTqaqedvLWteP+g7qt9PHKmZQhSo1TU/yD2CKgCcDAGhQ4uuvOnCbBvkvny7c3EKkBsi2iRZYCJe6bMduR0DdNEwLSZxOdTPIJ8xbaeuO3++iakvzCFmdOWRCg5rl3eJeT/LB+GZLM3sfx+Z18kATh+IKQeN8o20WQToxWYPh5bJax3DS2u9OIMIqtRlli9FG+g3sRDIMjHXkp0jA2ItuhZecIFEM3MEPksWYedbz6E2D4vPFaPIB97nQ+yYI980SI+5bjzqBaXraoeTRMmqv0RooruvOmq4c0txoAbT57DBxqUTOignW/0jhKFJLnDjtR9rgGtwSA/pdH36rK+s7NveDCBj9xb5zXpx7sNh48D72Px3wQs0ohu1Gf9ofu6eH3x2+/jQYOG3jBhNJWxKFx2CPg6MoK9+QzfisQOk/Jolq/dWvOal4eMZx1qppmvuZ/uRHZfXb3u5mLaWpytNGz4EIbDAiMGqsOtAWHsN6M0MlvWJ4senfl1lxPk0ZfErd+rjhz9QZfioGv7zHtj55eCeV+XnuuQTSpPwdrnpnCG/VjUwDLqqk="
  - secure: "YMOWTbpKcBlTlVdHf3R0oX4WMXW7oyIZoMMjDQs1ybh3iXnOWxuslylpjmn1dROrPqv52IxFfSj6L3QoZZ9lgmavg5/k2O/FQFVWeDLOUWQcqDN/G1/6zb8Kpv/YnlTdPNHkDJv9lLWwoKMn2dcKp5cDouzM3STbUNMAlxVmr6Fgwixjap3Gt+W6/ZWiHSbGJ7fmZPK7OJ6GGY7KWTQKMZvIMkdW2shEfk8KjP8Etl0CdEvno0uPEFFnbimxX4i/P8/qOmSEO6qYALF5i9QkfygCDK15hL7/YNZ/gCELUABQW01Gg5xrR4Y7gDdBACB9jwtL+5d3VZc/VHv9c1d17S2Eb5f4kfMxVJN+RGNV9oR5P5Ct3Jy1z1CtXGEbHXfrGk6nr55UXUyXVMN+KaAVzKWYBTFbIoaTZ201g4HijiRHTVKDrb1wojPkGtNkXgghUWU0D0raaP3uCTvdETzfb3XFQapFi5iCIbQNPO55Ur/i3r9j8/nizZAqsgkQq3GsBsbcbVOvAEfBpn8qzmlymciK7N4rT7PmuzqW6B310mkpr4heHoeIlj+EuvnIR3YkHzdyIweM0iKNRB9iUWgMMdzhYNcUS0uTkAnPh/QDFYcdPnBFU91pt3mLwNXPw7uYjl13q7DOA/1A122+ZxySllsPtxcJgwZ9SOhsuc6Y7uw="
  - secure: "xtMzInS9jWnq7o+8iAFIPHlgmX68hWABpuy80ghENvm22nV9MWuQEajQsdaoknp4Hhv9gHIwEVoFDj4GQLLY89QDj5GFe6FxSL9wV9pwSjJ2tUtEpfGqzcgKRpQiT/W6dNYsJ+RXs+NlzCbe2djStVu6DzdGlqQp1aZqlikYWqcxn3GA2YGpuwvrVL/H4ANl47X8liPKRfbJvVLStv4nfEeKmoHbHg4pCWhajSmn4KObH4E4Dg7qkwZ2S2q4DycX2z/T71uVfAjEDiWtKS4gAl0HJktE2SbE4k5mgpW8RGuYs6EVt9UiWIGQPnnr45NErEvEwWi0kbcDx1hFZH8Qp37kzXu32PKpNx7O72X/uVMJAe76cQZtnBGa4bLKWBV+C/FJ3Ex0zpA1w0ylQSTFHkmKQ/h4NW0cxLmn0I551hXFMASV3IEMqE/KE1CtrPf2W76xx22mZ0Bma0iYBi8KBQcAQTvFeUOy/xtFGc5d/+hCc4byhIhPEzT4hIc4pj7CZBbSuxOPQjwTKnrnKftlr2W9dlTu+FGVUI60mhkAGKRvLia76diNX5ZzOHhj2VJGupBmuxXW0uD3uC8nFBzYiKfgmYLBJvAzAZjBakypmYj2/hFo+ToyyrnoJKWZmDzfC45NLatvXmkJuZhK7ma4VX1LCMrzroX81vSEtvK4PWE="

#
# Required secure variables, add via
# travis encrypt --com SOMEVAR="secretvalue"
#
# CI_DEPLOY_USERNAME / CI_DEPLOY_PASSWORD
# Used in .m2/settings.xml for deploying into https://oss.sonatype.org/
# The user needs write permission for group net.sourceforge.pmd.*
#
# CI_SIGN_KEYNAME / CI_SIGN_PASSPHRASE
# Used in .m2/settings.xml
# GPG key used to sign the release jar before uploading to maven central
#

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0e6dd310db54b96c2653
      - https://webhooks.gitter.im/e/65efc1ea65175ad23ab6
      - https://webhooks.gitter.im/e/d93f85750d54f0a8623b
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
  email:
    recipients:
    - andreas.dangel@adangel.org
    on_success: change
    on_failure: always
